---
views:
  v1/pods:
    columns:
      - NAMESPACE
      - NAME
      - READY
      - RESTARTS
      - STATUS
      - AGE
      - CPU
      - MEM
      - "%CPU/R"
      - "%CPU/L"
      - "%MEM/R"
      - "%MEM/L"
      - IP
      - NODE
  v1/nodes:
    sortColumn: AGE:asc
    columns:
      - INTERNAL-IP
      - STATUS
      - TAINTS
      - VERSION
      - PODS
      - CPU
      - MEM
      - "%CPU"
      - "%MEM"
      - "CPU/A"
      - "MEM/A"
      - AGE
      - LABELS
  